//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Masters
{
    [Serializable]
    public class StartMoveMsg : Message
    {
        public const string k_RosMessageName = "masters_msgs/StartMove";
        public override string RosMessageName => k_RosMessageName;

        public bool start;

        public StartMoveMsg()
        {
            this.start = false;
        }

        public StartMoveMsg(bool start)
        {
            this.start = start;
        }

        public static StartMoveMsg Deserialize(MessageDeserializer deserializer) => new StartMoveMsg(deserializer);

        private StartMoveMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
        }

        public override string ToString()
        {
            return "StartMoveMsg: " +
            "\nstart: " + start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
