//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Masters
{
    [Serializable]
    public class AppControlServiceRequest : Message
    {
        public const string k_RosMessageName = "masters_msgs/AppControlService";
        public override string RosMessageName => k_RosMessageName;

        public sbyte command;

        public AppControlServiceRequest()
        {
            this.command = 0;
        }

        public AppControlServiceRequest(sbyte command)
        {
            this.command = command;
        }

        public static AppControlServiceRequest Deserialize(MessageDeserializer deserializer) => new AppControlServiceRequest(deserializer);

        private AppControlServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "AppControlServiceRequest: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
