//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Masters
{
    [Serializable]
    public class AppControlServiceResponse : Message
    {
        public const string k_RosMessageName = "masters_msgs/AppControlService";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public AppControlServiceResponse()
        {
            this.success = false;
        }

        public AppControlServiceResponse(bool success)
        {
            this.success = success;
        }

        public static AppControlServiceResponse Deserialize(MessageDeserializer deserializer) => new AppControlServiceResponse(deserializer);

        private AppControlServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "AppControlServiceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
