//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Masters
{
    [Serializable]
    public class ContactPointServiceResponse : Message
    {
        public const string k_RosMessageName = "masters_msgs/ContactPointService";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public Geometry.PointMsg position;

        public ContactPointServiceResponse()
        {
            this.success = false;
            this.position = new Geometry.PointMsg();
        }

        public ContactPointServiceResponse(bool success, Geometry.PointMsg position)
        {
            this.success = success;
            this.position = position;
        }

        public static ContactPointServiceResponse Deserialize(MessageDeserializer deserializer) => new ContactPointServiceResponse(deserializer);

        private ContactPointServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "ContactPointServiceResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
