//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Masters
{
    [Serializable]
    public class SystemStateServiceResponse : Message
    {
        public const string k_RosMessageName = "masters_msgs/SystemStateService";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SystemStateServiceResponse()
        {
            this.success = false;
        }

        public SystemStateServiceResponse(bool success)
        {
            this.success = success;
        }

        public static SystemStateServiceResponse Deserialize(MessageDeserializer deserializer) => new SystemStateServiceResponse(deserializer);

        private SystemStateServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SystemStateServiceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
